// Default option list: the "A Clash of Units" scoring-rule modification pool.
// Each entry is { label, value, category, group? }. The value is the increment; the
// +/- zones on the board decide whether it is applied as +value or -value.
// Category groups the bins into the mid-board buckets (can be turned off).
// Options sharing a `group` can be pooled into one bin with a mini board
// underneath (the "Pool range stats" setting), e.g. the Points Allowed ranges.
//
// Edit this file, commit and push to update the site. Visitors can also paste
// their own list in the Options panel (one per line: "Name +0.5 | Category | Group").

window.DEFAULT_OPTIONS = [
  // Roster
  { label: "Quarterbacks", value: "1", category: "Roster" },
  { label: "Running Backs", value: "1", category: "Roster" },
  { label: "Wide Receivers", value: "1", category: "Roster" },
  { label: "Tight Ends", value: "1", category: "Roster" },
  { label: "Kickers", value: "1", category: "Roster" },
  { label: "Defense", value: "1", category: "Roster" },
  { label: "Flex (W/R/T)", value: "1", category: "Roster" },
  { label: "Flex (W/R)", value: "1", category: "Roster" },
  { label: "Flex (W/T)", value: "1", category: "Roster" },
  { label: "Flex (Q/W/R/T)", value: "1", category: "Roster" },
  { label: "Flex (IDP)", value: "1", category: "Roster" },
  { label: "DL", value: "1", category: "Roster" },
  { label: "LB", value: "1", category: "Roster" },
  { label: "DB", value: "1", category: "Roster" },
  { label: "Bench", value: "1", category: "Roster" },
  // Passing
  { label: "Passing Yards", value: "0.04", category: "Passing" },
  { label: "Passing TDs", value: "3", category: "Passing" },
  { label: "Passing First Down", value: "1", category: "Passing" },
  { label: "2-pt Conversion (Pass)", value: "10", category: "Passing" },
  { label: "Pass Intercepted", value: "3", category: "Passing" },
  { label: "Pick 6 Thrown", value: "10", category: "Passing" },
  { label: "Pass Completed", value: "1", category: "Passing" },
  { label: "Incomplete Pass", value: "1", category: "Passing" },
  { label: "Pass Attempt", value: "1", category: "Passing" },
  { label: "QB Sacked", value: "3", category: "Passing" },
  { label: "40+ Yard Completion Bonus", value: "5", category: "Passing" },
  { label: "40+ Yard Pass TD Bonus", value: "10", category: "Passing" },
  { label: "50+ Yard Pass TD Bonus", value: "10", category: "Passing" },
  { label: "300-399 Yard Passing Game", value: "10", category: "Passing" },
  { label: "400+ Yard Passing Game", value: "10", category: "Passing" },
  { label: "25+ Pass Completions", value: "5", category: "Passing" },
  { label: "First Down Bonus - QB", value: "1", category: "Passing" },
  // Rushing
  { label: "Rushing Yards", value: "0.1", category: "Rushing" },
  { label: "Rushing TD", value: "3", category: "Rushing" },
  { label: "Rushing First Down", value: "2", category: "Rushing" },
  { label: "2-pt Conversion (Rush)", value: "10", category: "Rushing" },
  { label: "Rush Attempt", value: "1", category: "Rushing" },
  { label: "40+ Yard Rush Bonus", value: "10", category: "Rushing" },
  { label: "40+ Yard Rush TD Bonus", value: "10", category: "Rushing" },
  { label: "50+ Yard Rush TD Bonus", value: "10", category: "Rushing" },
  { label: "100-199 Yard Rushing Game", value: "5", category: "Rushing" },
  { label: "200+ Yard Rushing Game", value: "50", category: "Rushing" },
  { label: "20+ Carries", value: "5", category: "Rushing" },
  { label: "First Down Bonus - RB", value: "2", category: "Rushing" },
  // Receiving
  { label: "Reception", value: "1", category: "Receiving" },
  { label: "Receiving Yards", value: "0.1", category: "Receiving" },
  { label: "Receiving TD", value: "3", category: "Receiving" },
  { label: "Receiving First Down", value: "1", category: "Receiving" },
  { label: "2-pt Conversion (Rec)", value: "10", category: "Receiving" },
  { label: "0-4 Yard Reception Bonus", value: "2", category: "Receiving" },
  { label: "5-9 Yard Reception Bonus", value: "2", category: "Receiving" },
  { label: "10-19 Yard Reception Bonus", value: "2", category: "Receiving" },
  { label: "20-29 Yard Reception Bonus", value: "3", category: "Receiving" },
  { label: "30-39 Yard Reception Bonus", value: "5", category: "Receiving" },
  { label: "40-49 Yard Reception Bonus", value: "5", category: "Receiving" },
  { label: "50+ Yard Reception Bonus", value: "5", category: "Receiving" },
  { label: "Reception Bonus - RB", value: "2", category: "Receiving" },
  { label: "Reception Bonus - WR", value: "1", category: "Receiving" },
  { label: "Reception Bonus - TE", value: "2", category: "Receiving" },
  { label: "100-199 Yard Receiving Game", value: "5", category: "Receiving" },
  { label: "200+ Yard Receiving Game", value: "50", category: "Receiving" },
  { label: "First Down Bonus - WR", value: "2", category: "Receiving" },
  { label: "First Down Bonus - TE", value: "3", category: "Receiving" },
  // Kicking
  { label: "FG Made", value: "3", category: "Kicking" },
  { label: "FG Made (0-19 yards)", value: "50", category: "Kicking" },
  { label: "FG Made (20-29 yards)", value: "5", category: "Kicking" },
  { label: "FG Made (30-39 yards)", value: "5", category: "Kicking" },
  { label: "FG Made (40-49 yards)", value: "5", category: "Kicking" },
  { label: "FG Made (50+ yards)", value: "5", category: "Kicking" },
  { label: "Points per FG yard", value: "0.2", category: "Kicking" },
  { label: "Points per FG yard over 30", value: "0.3", category: "Kicking" },
  { label: "PAT Made", value: "3", category: "Kicking" },
  { label: "FG Missed", value: "5", category: "Kicking" },
  { label: "FG Missed (0-19 yards)", value: "100", category: "Kicking" },
  { label: "FG Missed (20-29 yards)", value: "50", category: "Kicking" },
  { label: "FG Missed (30-39 yards)", value: "10", category: "Kicking" },
  { label: "FG Missed (40-49 yards)", value: "10", category: "Kicking" },
  { label: "FG Missed (50+ yards)", value: "10", category: "Kicking" },
  { label: "PAT Missed", value: "10", category: "Kicking" },
  // Team Defense
  { label: "Defense TD", value: "10", category: "Team Defense" },
  { label: "Points Allowed (0)", value: "50", category: "Team Defense", group: "Points Allowed" },
  { label: "Points Allowed (1-6)", value: "10", category: "Team Defense", group: "Points Allowed" },
  { label: "Points Allowed (7-13)", value: "10", category: "Team Defense", group: "Points Allowed" },
  { label: "Points Allowed (14-20)", value: "5", category: "Team Defense", group: "Points Allowed" },
  { label: "Points Allowed (21-27)", value: "5", category: "Team Defense", group: "Points Allowed" },
  { label: "Points Allowed (28-34)", value: "5", category: "Team Defense", group: "Points Allowed" },
  { label: "Points Allowed (35+)", value: "10", category: "Team Defense", group: "Points Allowed" },
  { label: "Points per Point Allowed", value: "1", category: "Team Defense" },
  { label: "Less Than 100 Total Yards Allowed", value: "100", category: "Team Defense", group: "Yards Allowed" },
  { label: "100-199 Yards Allowed", value: "10", category: "Team Defense", group: "Yards Allowed" },
  { label: "200-299 Yards Allowed", value: "5", category: "Team Defense", group: "Yards Allowed" },
  { label: "300-349 Yards Allowed", value: "5", category: "Team Defense", group: "Yards Allowed" },
  { label: "350-399 Yards Allowed", value: "5", category: "Team Defense", group: "Yards Allowed" },
  { label: "400-449 Yards Allowed", value: "10", category: "Team Defense", group: "Yards Allowed" },
  { label: "450-499 Yards Allowed", value: "10", category: "Team Defense", group: "Yards Allowed" },
  { label: "500-549 Yards Allowed", value: "10", category: "Team Defense", group: "Yards Allowed" },
  { label: "550+ Yards Allowed", value: "50", category: "Team Defense", group: "Yards Allowed" },
  { label: "Points per Yards Allowed", value: "0.05", category: "Team Defense" },
  { label: "3 and Out", value: "3", category: "Team Defense" },
  { label: "4th Down Stop", value: "5", category: "Team Defense" },
  { label: "Hit on QB (Team Def)", value: "2", category: "Team Defense" },
  { label: "Sack (Team Def)", value: "3", category: "Team Defense" },
  { label: "Sack Yards (Team Def)", value: "0.3", category: "Team Defense" },
  { label: "Interception (Team Def)", value: "3", category: "Team Defense" },
  { label: "Interception Yards (Team Def)", value: "0.3", category: "Team Defense" },
  { label: "Fumble Recovery (Team Def)", value: "5", category: "Team Defense" },
  { label: "Fumble Return Yards (Team Def)", value: "0.5", category: "Team Defense" },
  { label: "Tackle For Loss (Team Def)", value: "3", category: "Team Defense" },
  { label: "Assisted Tackle (Team Def)", value: "1", category: "Team Defense" },
  { label: "Solo Tackle (Team Def)", value: "0.5", category: "Team Defense" },
  { label: "Tackle (Team Def)", value: "0.5", category: "Team Defense" },
  { label: "Safety (Team Def)", value: "10", category: "Team Defense" },
  { label: "Forced Fumble (Team Def)", value: "3", category: "Team Defense" },
  { label: "Blocked Kick", value: "10", category: "Team Defense" },
  { label: "Forced Punt", value: "2", category: "Team Defense" },
  { label: "Pass Defended (Team Def)", value: "2", category: "Team Defense" },
  { label: "2-pt Conversion Returns", value: "100", category: "Team Defense" },
  { label: "Missed FG Return Yards (Team Def)", value: "10", category: "Team Defense" },
  { label: "Blocked Kick Return Yards (Team Def)", value: "10", category: "Team Defense" },
  // Special Teams
  { label: "Special Teams TD (D/ST)", value: "10", category: "Special Teams" },
  { label: "Special Teams Forced Fumble (D/ST)", value: "10", category: "Special Teams" },
  { label: "Special Teams Fumble Recovery (D/ST)", value: "10", category: "Special Teams" },
  { label: "Special Teams Solo Tackle (D/ST)", value: "3", category: "Special Teams" },
  { label: "Punt Return Yards (D/ST)", value: "0.3", category: "Special Teams" },
  { label: "Kick Return Yards (D/ST)", value: "0.2", category: "Special Teams" },
  { label: "Special Teams Player TD", value: "10", category: "Special Teams" },
  { label: "Special Teams Player Forced Fumble", value: "10", category: "Special Teams" },
  { label: "Special Teams Player Fumble Recovery", value: "10", category: "Special Teams" },
  { label: "Special Teams Player Solo Tackle", value: "3", category: "Special Teams" },
  { label: "Player Punt Return Yards", value: "0.3", category: "Special Teams" },
  { label: "Player Kick Return Yards", value: "0.2", category: "Special Teams" },
  // Misc
  { label: "Fumble", value: "3", category: "Misc" },
  { label: "Fumble Lost", value: "5", category: "Misc" },
  { label: "Fumble Recovery TD", value: "10", category: "Misc" },
  { label: "100-199 Combined Rush + Rec Yards", value: "5", category: "Misc" },
  { label: "200+ Combined Rush + Rec Yards", value: "10", category: "Misc" },
  // IDP
  { label: "IDP Touchdown", value: "10", category: "IDP" },
  { label: "Sack (IDP)", value: "3", category: "IDP" },
  { label: "Sack Yards (IDP)", value: "0.3", category: "IDP" },
  { label: "Hit on QB (IDP)", value: "2", category: "IDP" },
  { label: "Tackle (IDP)", value: "0.5", category: "IDP" },
  { label: "Tackle For Loss (IDP)", value: "3", category: "IDP" },
  { label: "Blocked Punt, PAT, or FG (IDP)", value: "10", category: "IDP" },
  { label: "Interception (IDP)", value: "3", category: "IDP" },
  { label: "Interception Return Yards (IDP)", value: "0.3", category: "IDP" },
  { label: "Fumble Recovery (IDP)", value: "5", category: "IDP" },
  { label: "Fumble Recovery Return Yards (IDP)", value: "0.5", category: "IDP" },
  { label: "Forced Fumble (IDP)", value: "3", category: "IDP" },
  { label: "Safety (IDP)", value: "10", category: "IDP" },
  { label: "Assisted Tackle (IDP)", value: "1", category: "IDP" },
  { label: "Solo Tackle (IDP)", value: "0.5", category: "IDP" },
  { label: "Pass Defended (IDP)", value: "2", category: "IDP" },
  { label: "10+ Tackle Bonus", value: "5", category: "IDP" },
  { label: "2+ Sack Bonus", value: "5", category: "IDP" },
  { label: "3+ Pass Defended Bonus", value: "10", category: "IDP" },
  { label: "50+ Yard Interception Return TD Bonus", value: "10", category: "IDP" },
  { label: "50+ Yard Fumble Recovery Return TD Bonus", value: "50", category: "IDP" },
];
